= v1
:imagesdir: ../../assets/img/course-java-core

== Intro

* Программное обеспечение, которое будет использоваться в процессе, находится в блоке *Software*.
* Задания будут выполняться в репозиториях:
** `course-java-core`
** `course-java-design`
* По мере необходимости делаем *fork* и ставим *star* для соответствующего репозитория.
* *One lesson* ~ *One or more themes* ~ *Many practice tasks* ~ *One branch with theme name*.
* *Branch* (ветка) для *theme* (тема) содержит стартовый код для текущей темы.
* Выполнение задания по какой-то `theme` происходит ТОЛЬКО в соответствующем `branch`.
* Теоретический материал будет в печатном виде и в виде онлайн-документации (link:https://wiki-gl.dmitryrakovets.com/[wiki]).

== Processes

=== Elementary lessons (2-nd - 6-th lesson)

Основные концепции:

* На выполнение задания для темы отводится 6 дней, следующих за днем когда занятие по этой теме состоялось.
* Работа с *Git* осуществляется с помощью *GUI* в *Intellij IDEA*.
* Для проверки правильности выполнения задания, запускаются соответствующие *unit-tests*.
* После выполнения одного *task* требуется сделать *commit* этого *task* с понятным описание.
* После выполнения заданий по текущей теме (всех или тех, с которыми справились), следует сделать *push* в *remote repository*

==== Процесс работы над заданиями/темами.

.Схема процесса работы над заданиями/темами:
image::v1.svg[Process]

* *TO DO*
** после окончания занятия по какой-то теме, дается практическое задание по этой теме

* *IN PROGRESS*
** прочитать теоретический материал (feedback: theory test with Google Form; влияет на GRADE)
** выполнить задания предложенные преподавателем (feedback: unit-tests, manual review with GitHub; влияет на GRADE):
** выполнить задания в рабочей тетради (контроль: manual review with trainer, не влияет на GRADE)

* *TO REVIEW*
** Сделать *Pull Request* в соответствующую ветку repository преподавателя.

* *TO FIX*
** Если после *code review* есть замечания по коду, то их необходимо устранить.
** Если не все задания были выполнены, то следует разобраться в правильно выполненном задании и реализовать его.

* *APPROVED*
** Проведен *code review* и все задания выполнены правильно, без значительных недочетов.

* *DONE*
** Все необходимые действия (*code review*, выставление отметок, закрытие *PR* и т.д.) над данным задание выполнены.

=== Intermediate lessons (Other lessons)

//todo

=== Last lesson

//todo

==== Прокачиваем аккаунт на LinkedIn

* Оформить текущее место работы: `IT academy`, `Trainee`
* Добавить навыки:
** Java
** OOP
** JUnit
** Git
* Добавить в *Network* одногруппников и тренера.
* Подтвердить навыки одногруппников и тренера.
