= v1
:imagesdir: ../../assets/img/course-java-core

* *IDE*: IntelliJ IDEA Community Edition.
* *VCS*: работа с локальным git-репозиторием и загрузка в удаленный git-репозиторий с помощью *GUI* текущей *IDE*.

== Intro

* *Одно занятие* ~ *Одна или больше тем* ~ *Много практических заданий* ~ *Один branch, который содержит стартовый код для темы*.
* Теоретический материал:
** печатное учебное пособие
** link:https://wiki-gl.dmitryrakovets.com/[wiki]
** презентации с занятий

== Elementary lessons

.Схема процесса работы над заданиями/темами:
image::v1.svg[Process]

* *TO DO*
** После окончания занятия по какой-то теме, дается практическое задание по этой теме.
** На выполнение задания отводится 6 дней, следующих за днем когда занятие по этой теме состоялось.

* *IN PROGRESS*
** Прочитать теоретический материал (*feedback*: тест по теории с помощью *Google Forms*; влияет на GRADE).
** Выполнить задания предложенные преподавателем (*feedback*: unit-tests, code review с помощью *GitHub*; влияет на GRADE):
*** После выполнения одного *task*/*specification of task*/*project* требуется сделать *commit* с понятным описание фиксируемых изменений.
** Опционально выполнить задания в рабочей тетради (*feedback*: code review на занятии, не влияет на GRADE).

* *TO REVIEW*
** После выполнения заданий по текущей теме (всех или только тех, с которыми справились или успели сделать), следует сделать *push* в *remote repository*.
** Сделать *Pull Request* в соответствующий тренерский repository и branch.

WARNING: Часто для *Pull Request*/*Merge Request* проектов (чаще open-source), выставляют набор требований, которым он должен соответствовать. Поэтому следует придерживаться этих требований, для того, что бы *PR*/*MR* не был отклонен, по причине не соответствия этим требованиям.

* *TO FIX*
** Если после *code review* есть замечания по коду, то их необходимо устранить.
** Если не все задания были выполнены, то следует разобраться в правильно выполненном задании и реализовать его.

* *APPROVED*
** Проведен *code review* и все задания выполнены правильно, без значительных недочетов.

* *DONE*
** Все необходимые действия (*code review*, выставление отметок, закрытие *PR* и т.д.) над данным задание выполнены.

NOTE: Для корректного выполнения задания следует посмотреть видео link:https://youtu.be/Hda0ZtG4ho0[How to do homework?^].
