= Common

* Необходимо выполнить действия описанные в блоке *Communication*.

== Communication

Описывает инструменты и способы взаимодействия в процессе обучения.

=== Telegram

* Зарегистрироваться.
* Отправить сообщение тренеру, которое содержит Ваше имя и фамилию на АНГЛИЙСКОМ языке, используя никнейм `@rakovets` или номер `+375296678238`.
** В случае возникновения проблем с поиском, напишите тренеру на email `dmitryrakovets@gmail.com`.
* Временно отключить настройки политики по добавлению в группу, так как тренер не сможет добавить в группу.
* Ожидать добавления в 2 группы:
** `${group-name}-dev` - используется для ежедневного взаимодействия в группе.
** `${group-name}-prod` - используется для объявлений и решения критических вопросов/проблем, которые не могли быть решены в первой, так как тренер мог не увидеть/прочитать Ваше сообщение.

=== Gmail

* Зарегистрироваться.
* Подписаться на *YouTube* канал: link:https://www.youtube.com/channel/UCIztUGTxSCyqksE3HxFgI_w[Dmitry Rakovets^].
* Отправить сообщение тренеру в Telegram, которое содержит Ваш *email* (ТОЛЬКО *gmail*).
** На этот *email*, предоставляется доступ к закрытым видео на *YouTube*, если таковые имеются.
* Ожидать доступа к *электронному журналу*, который содержит текущие отметки.

=== GitHub

* Зарегистрироваться.
* Подписаться на пользователя: link:https://www.github.com/rakovets[Dmitry Rakovets^].
* Поставить *star* для репозиториев:
** `wiki`
** `presentation`
* Будет использоваться для хранения исходного кода.

=== LinkedIn

* Зарегистрироваться.
* Отправить `Connect` пользователю: link:https://www.linkedin.com/in/rakovets/[Dmitry Rakovets^].
* Будет использоваться для увеличения сети контактов как профессионала.
