= Common

Данный блок содержит общие процессы, независимо от курса.

== Communication

В процессе занятий необходимо взаимодействовать как с тренером, так и с другими участниками. Для этого будут использоваться инструменты:

* *Telegram* - для ежедневного общения и объявлений.
* *Google Account* - для доступа к журналу, презентациям, видео на *YouTube* и прочим артефактам.
* *GitHub* - для хранения кода и любых взаимодействий относительно кода (т.е. практических заданий).
* *LinkedIn* - для взаимодействия после курса (сеть профессиональных контактов).

=== Telegram

* Зарегистрироваться.
* Отправить сообщение тренеру, которое содержит Ваше имя и фамилию на АНГЛИЙСКОМ языке, используя его никнейм `@rakovets` или номер `+375296678238`.
** В случае возникновения проблем с поиском, напишите тренеру на email `dmitryrakovets@gmail.com`.
* Временно отключить настройки политики по добавлению в группу, так как тренер не сможет добавить в группу.
* Ожидать добавления в 2 группы:
** `${group-name}-dev` - используется для ежедневного взаимодействия в группе.
** `${group-name}-prod` - используется для объявлений и решения критических вопросов/проблем, которые не могли быть решены в первой, так как тренер мог не увидеть/прочитать Ваше сообщение.

=== Google Account

* Зарегистрироваться.
* Подписаться на *YouTube* канал: link:https://www.youtube.com/channel/UCIztUGTxSCyqksE3HxFgI_w[Dmitry Rakovets^].
* Отправить сообщение тренеру в *Telegram*, которое содержит Ваш *gmail* (email для *Google Account*).
* Ожидать доступа к директории на *Google Drive*, которая содержит:
** электронный журнал
** презентации
** прочие артефакты

=== GitHub

* Зарегистрироваться.
* Подписаться на пользователя: link:https://www.github.com/rakovets[Dmitry Rakovets^].
* При использовании чужих репозиториев или кода из них, хорошей практикой считается ставить *star* (*like*) для этого репозитория.

=== LinkedIn

* Зарегистрироваться.
* Отправить `Connect` пользователю: link:https://www.linkedin.com/in/rakovets/[Dmitry Rakovets^].
