= Course 'Java for Back end'

== Pet-project

Данный проект является инструкцией по работе над учебным проектом.

=== Цель

* упростить процесс разработки собственного проекта

=== Задачи

* познакомить с этапами разработки продукта на базе общепринятых методологий;
* познакомить с инструментами, которые позволяет упростить работу на некоторых этапах разработки;
* выработать правильный процесс работы над конкретными задачами.

=== Этапы разработки

Этапы разработки подразумевают наличие какой-то общей идеи. Реализация этой идеи, в виде программного продукта, решит какую-то реальную проблему клиентов данного программного продукта.

Все этапы, описанные ниже, подразумеваю циклическое исполнение, а результатом каждого цикла будет являться инкремент (т.е. какая-то минимальная работающая функциональность):

Этапы разработки:

* планирование
* разработка UML диаграмм классов
* разработка структуры БД
* разбиение запланированной функциональности на задачи
* реализация задач
* тестирование задач

==== Планирование

. Придумать идею для функциональности, которая сделает *product* лучше.
. Выделить *epics* для этой идеи, т.е. разбить ее на несколько атомарных глобальных функций.
. Для каждого *epic* выделить *stories*, реализация которых позволит считать данную функциональность завершенной. Пример *story*:

____
_As a_ *user*, _I want to_ *register in the service* _so that I can_ *create my own garage*
____

Для планирования можно использовать различные инструменты. Например, можно использовать сервис для построения *Mind Map*: link:https://coggle.it[coggle]

==== Разработка UML диаграмм классов

Для разработки UML диаграмм можно использовать различные инструменты. Например, можно использовать сервис link:https://cdraw.io[draw.io]

==== Разработка структуры БД

Для разработки структуры БД можно использовать различные инструменты. Например, можно использовать сервис https://www.dbdesigner.net[DB DESIGNER]

==== Разбиение запланированной функциональности на задачи

Далее идет процесс разбиения *story* для *project* на несколько *ticket* (задача) для разработки. На этом этапе на *dashboard* необходимого *project* в колонке *To do* создаются *tickets*, которые позволяют реализовать данную *story*. Как пример *story* _As a user, I want to register in the service so that I can create my own garage_ потребует как минимум создания одного *ticket*:

----
BS-1. feat: registration user

- [ ] registration view
- [ ] controller
- [ ] service
- [ ] repository
- [ ] entity
----

Можно разбивать *story* на более мелкие *tickets*, в зависимости от сложности *ticket* и возможности команды параллельно работать над *tickets* для одной *story*, например:

----
- BS-1. feat: create registration view
- BS-2. feat: create registration controller
- BS-3. feat: create registration service
- BS-4. feat: create registration repository
- BS-5. feat: create registration entity
----

==== Реализация задач

*Ticket* на этом этапе перемещается на *dashboard* для *project* из колонки *To do* в колонку *In progress* и с помощью таймера засекается время работы над задачей.

При технической реализации задач обычно применяется документация или различные гайды тех технологий, которые используются в проекте. Примером может служить:

- link:https://spring.io/guides[Spring Guides]
- link:https://docs.spring.io/spring/docs/current/spring-framework-reference/[Spring Framework Documentation]
- link:https://hibernate.org/orm/documentation/6.0/[Hibernate ORM. Documentation - 6.0]

Для решения проблем, которые могут возникнуть при реализации, использую любую поисковую систему. Чаще всего решения данных проблем можно найти на сервисе link:https://stackoverflow.com/[stackoverflow]

==== Тестирование задач

Разработчики, для тестирования новой или уже существующей функциональности:

* пишут *unit-tests*, которые позволяют протестировать небольшую её часть;
* применяют различные инструменты для модульных тестов. Например, используют link:https://www.postman.com/[*Postman*] для тестирования *API* разработанного *REST-service*;
* проводят функциональное тестирование всего продукта. Фактически, эмулируют поведение клиента и смотрят как сервис реагирует на это.

После этого этапа *ticket* перемещается на *dashboard* для *project* из колонки *In progress* в колонку *Done* и в конец описания этого *ticket* добавляется время затраченное на его реализацию и тестирование. Например, когда затраченное на *ticket* время 1 день (8 часов) и 4 часа, тогда делается запись `1d 4h`.
